version: '2'

services:
  chess-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/cpp-rest-api
    working_dir: /cpp-rest-api
    command: bash -c "make -f client.mak && ./client `cat /etc/hosts | grep 172 | cut -c 1-6`"
